import type {
  DiaKnowledgeCatalog,
  DiaKnowledgeConcept,
  KnowledgeAuthorityTier,
  KnowledgeConceptKind,
  KnowledgeDefinitionStatus,
  KnowledgeDomain,
  KnowledgeExecutionEligibility,
  KnowledgeRelation,
  KnowledgeSourceRef,
  KnowledgeStatus,
} from './schema'

export const SOURCE_IDS = {
  encyclopedia: 'dia-src-theatre-encyclopedia-v1',
  mindmap: 'dia-src-directing-mindmap-v1',
  zhongxi: 'dia-src-zhongxi-glossary-v1',
  glossary2018: 'dia-src-glossary-2018-v1',
  seagull: 'dia-src-seagull-cn-v1',
  cyrano: 'dia-src-cyrano-cn-v1',
} as const

const VERSION = 'dia-knowledge-v0.1'
const UAF_STAGE_TERMS = {
  title: 'University of Alaska Fairbanks Theatre & Film Student Handbook — Theatre Terms',
  url: 'https://www.uaf.edu/theatrefilm/student-handbook.php',
  authorityTier: 'institutional_teaching' as const,
}
const COLUMBIA_MISE_EN_SCENE = {
  title: 'Columbia Film Language Glossary — Mise-en-Scène',
  url: 'https://filmglossary.ccnmtl.columbia.edu/term/mise-en-scene/',
  authorityTier: 'institutional_teaching' as const,
}
const UCF_BRECHT = {
  title: 'University of Central Florida — Bertolt Brecht’s Dramatic Structure',
  url: 'https://cah.ucf.edu/news/bertolt-brechts-dramatic-structure/',
  authorityTier: 'institutional_teaching' as const,
}
const TIAN_HAN_FOUNDATION_BLACK_SLAVE = {
  title: '田汉基金会 — 孙维世：忆欧阳予倩创作《黑奴恨》',
  url: 'https://www.tianhanfoundation.org/news_20/283.html',
  authorityTier: 'authoritative_reference' as const,
}
const HZNU_BLACK_SLAVE_RESEARCH = {
  title: '杭州师范大学《还原一个真实的春阳社》',
  url: 'https://rwxy.hznu.edu.cn/upload/resources/file/2022/12/28/7759474.pdf',
  authorityTier: 'peer_reviewed' as const,
}

type ConceptSeed = {
  id: string
  label: string
  canonicalLabel?: string
  definition: string
  aliases?: string[]
  relations?: KnowledgeRelation[]
  positiveExamples?: string[]
  contrastExamples?: string[]
  executableIntents?: string[]
  confidence?: number
  sourceRefs?: KnowledgeSourceRef[]
  authorityTier?: KnowledgeAuthorityTier
  conceptKind?: Exclude<KnowledgeConceptKind, 'example_pattern'>
  executionEligibility?: KnowledgeExecutionEligibility
  authorityRefs?: {
    title: string
    url: string
    authorityTier: Exclude<KnowledgeAuthorityTier, 'exam_notes'>
  }[]
  definitionStatus?: KnowledgeDefinitionStatus
  tradition?: string
  disputedNotes?: string[]
  historicalAttributions?: {
    founders?: string[]
    proposers?: string[]
    participants?: string[]
    adapters?: string[]
  }
}

const relation = (type: KnowledgeRelation['type'], targetId: string): KnowledgeRelation => ({
  type,
  targetId,
})

const concepts = (
  domain: KnowledgeDomain,
  status: KnowledgeStatus,
  defaultKind: Exclude<KnowledgeConceptKind, 'example_pattern'>,
  defaultExecutionEligibility: KnowledgeExecutionEligibility,
  sourceRefs: KnowledgeSourceRef[],
  seeds: ConceptSeed[],
): DiaKnowledgeConcept[] =>
  seeds.map((seed) => {
    const conceptKind = seed.conceptKind ?? defaultKind
    const executableIntents = status === 'ACTIVE' ? (seed.executableIntents ?? []) : []
    const definitionStatus =
      seed.definitionStatus ??
      (conceptKind === 'stage_term' ||
      conceptKind === 'spatial_relation' ||
      conceptKind === 'operation'
        ? 'operational'
        : 'descriptive')
    const executionEligibility = seed.executionEligibility ?? defaultExecutionEligibility
    return {
      id: seed.id,
      label: seed.label,
      canonicalLabel: seed.canonicalLabel ?? seed.label,
      conceptKind,
      domain,
      status,
      executionEligibility,
      authorityTier: seed.authorityTier ?? 'exam_notes',
      definitionStatus,
      tradition: seed.tradition ?? 'cross_tradition_working_vocabulary',
      authorityRefs: seed.authorityRefs ?? [],
      definition: seed.definition,
      aliases: seed.aliases ?? [],
      disputedNotes: seed.disputedNotes ?? [],
      historicalAttributions: {
        founders: seed.historicalAttributions?.founders ?? [],
        proposers: seed.historicalAttributions?.proposers ?? [],
        participants: seed.historicalAttributions?.participants ?? [],
        adapters: seed.historicalAttributions?.adapters ?? [],
      },
      relations: seed.relations ?? [],
      positiveExamples: seed.positiveExamples ?? [],
      contrastExamples: seed.contrastExamples ?? [],
      executableIntents,
      sourceRefs: seed.sourceRefs ?? sourceRefs,
      confidence: seed.confidence ?? 0.82,
      version: VERSION,
    }
  })

const assetRefs: KnowledgeSourceRef[] = [
  {
    sourceId: SOURCE_IDS.encyclopedia,
    locator: '“戏剧导演艺术”章／舞台空间与舞台美术相关条目',
    role: 'candidate_definition',
  },
  {
    sourceId: SOURCE_IDS.glossary2018,
    locator: '第10页“透视布景、檐幕、侧幕”及第58页“景片”相关条目',
    role: 'candidate_definition',
  },
]
const flatRefs: KnowledgeSourceRef[] = [
  {
    sourceId: SOURCE_IDS.glossary2018,
    locator: '第10页舞台布景条目及第58页“景片”相关条目',
    role: 'candidate_definition',
  },
  {
    sourceId: SOURCE_IDS.encyclopedia,
    locator: '“戏剧导演艺术”章／舞台美术与演出空间相关条目',
    role: 'candidate_definition',
  },
]
const spatialRefs: KnowledgeSourceRef[] = [
  {
    sourceId: SOURCE_IDS.zhongxi,
    locator: '第42页“舞台区位、舞台焦点”条目',
    role: 'candidate_definition',
  },
  {
    sourceId: SOURCE_IDS.glossary2018,
    locator: '第24页“舞台区位、舞台焦点”及第61页舞台空间相关条目',
    role: 'candidate_definition',
  },
  {
    sourceId: SOURCE_IDS.mindmap,
    locator: '第1页“舞台调度”分支',
    role: 'candidate_definition',
  },
]
const directingRefs: KnowledgeSourceRef[] = [
  {
    sourceId: SOURCE_IDS.encyclopedia,
    locator: '“戏剧导演艺术”章',
    role: 'candidate_definition',
  },
  {
    sourceId: SOURCE_IDS.mindmap,
    locator: '第1页导演学知识结构图',
    role: 'candidate_definition',
  },
  {
    sourceId: SOURCE_IDS.zhongxi,
    locator: '第38—42页表演与导演条目',
    role: 'candidate_definition',
  },
]
const dramaturgyRefs: KnowledgeSourceRef[] = [
  {
    sourceId: SOURCE_IDS.encyclopedia,
    locator: '“戏剧概论”章及“戏剧导演艺术”章／剧本分析部分',
    role: 'candidate_definition',
  },
  {
    sourceId: SOURCE_IDS.mindmap,
    locator: '第1页“舞台事件与舞台行动、剧本分析”分支',
    role: 'candidate_definition',
  },
]
const performanceRefs: KnowledgeSourceRef[] = [
  {
    sourceId: SOURCE_IDS.encyclopedia,
    locator: '“戏剧表演艺术”章',
    role: 'candidate_definition',
  },
  {
    sourceId: SOURCE_IDS.zhongxi,
    locator: '第38—42页表演艺术相关条目',
    role: 'candidate_definition',
  },
]

const activeStageAssets = concepts('stage_assets', 'ACTIVE', 'asset', 'allowed', assetRefs, [
  {
    id: 'stage-object',
    executionEligibility: 'proposal_only',
    label: '舞台物件',
    definition: '在演出空间中被布置、使用或形成空间关系的可识别实体。',
    aliases: ['舞台对象', '舞台物体'],
    relations: [relation('broader_than', 'platform'), relation('broader_than', 'chair')],
  },
  {
    id: 'platform',
    label: '台块',
    definition: '用于抬高、分层或组织表演区域的可移动舞台平台。',
    aliases: ['舞台台块', '平台台块'],
    relations: [relation('narrower_than', 'stage-object'), relation('supports', 'spatial-level')],
    executableIntents: ['place_platform'],
    confidence: 0.68,
  },
  {
    id: 'chair',
    label: '椅子',
    definition: '可供表演者坐用并参与场面构图的舞台家具。',
    aliases: ['座椅'],
    relations: [relation('narrower_than', 'stage-object')],
    executableIntents: ['place_chair'],
  },
  {
    id: 'table',
    label: '桌子',
    definition: '可供表演者围绕、使用并组织空间关系的舞台家具。',
    aliases: ['桌台'],
    relations: [relation('narrower_than', 'stage-object')],
    executableIntents: ['place_table'],
  },
  {
    id: 'stair',
    label: '阶梯',
    definition: '连接不同高度并形成上下行动路线的舞台构件。',
    aliases: ['台阶', '楼梯'],
    relations: [relation('narrower_than', 'stage-object'), relation('supports', 'spatial-level')],
    executableIntents: ['place_stair'],
  },
  {
    id: 'bench',
    label: '长凳',
    definition: '可供多人坐用并形成横向空间基准的舞台家具。',
    aliases: ['长椅'],
    relations: [relation('narrower_than', 'stage-object')],
    executableIntents: ['place_bench'],
  },
  {
    id: 'curtain',
    label: '帷幕',
    definition: '用于分隔、遮蔽或界定舞台空间的悬挂软质幕体。',
    aliases: ['幕布', '舞台帷幕'],
    relations: [
      relation('broader_than', 'wing-curtain'),
      relation('broader_than', 'border-curtain'),
    ],
    executableIntents: ['place_curtain'],
  },
  {
    id: 'wing-curtain',
    label: '侧幕',
    definition: '设置在舞台两侧、用于遮蔽侧台并限定表演口的幕体。',
    aliases: ['边幕'],
    relations: [relation('narrower_than', 'curtain'), relation('supports', 'occlusion')],
    executableIntents: ['place_wing_curtain'],
  },
  {
    id: 'border-curtain',
    label: '檐幕',
    definition: '悬挂在舞台上方、用于遮蔽上部设备并压缩可见画框的横幕。',
    aliases: ['横幕'],
    relations: [relation('narrower_than', 'curtain'), relation('supports', 'occlusion')],
    executableIntents: ['place_border_curtain'],
  },
])

const activeScenicFlats = concepts('scenic_flats', 'ACTIVE', 'asset', 'allowed', flatRefs, [
  {
    id: 'scenic-flat',
    label: '景片',
    definition: '以片状结构构成布景表面、边界或开口的舞台景物单元。',
    aliases: ['布景片', '舞台景片'],
    relations: [relation('broader_than', 'single-flat'), relation('broader_than', 'door-flat')],
    executableIntents: ['place_scenic_flat'],
  },
  {
    id: 'single-flat',
    label: '单片景片',
    definition: '由一个独立片面构成、没有联片折叠关系的景片。',
    aliases: ['单联景片'],
    relations: [
      relation('narrower_than', 'scenic-flat'),
      relation('distinct_from', 'double-fold-flat'),
    ],
    executableIntents: ['place_single_flat'],
    confidence: 0.65,
  },
  {
    id: 'double-fold-flat',
    label: '二联景片',
    definition: '两个片面以活动连接形成、可改变夹角的联体景片。',
    aliases: ['双联景片', '两联景片'],
    relations: [relation('narrower_than', 'scenic-flat'), relation('part_of', 'hinge')],
    executableIntents: ['place_double_flat'],
    confidence: 0.64,
  },
  {
    id: 'triple-fold-flat',
    label: '三联景片',
    definition: '三个片面以活动连接形成、可折转成多段轮廓的联体景片。',
    aliases: ['三折景片'],
    relations: [relation('narrower_than', 'scenic-flat'), relation('part_of', 'hinge')],
    executableIntents: ['place_triple_flat'],
    confidence: 0.63,
  },
  {
    id: 'door-flat',
    label: '门景片',
    definition: '带门洞或门体构造、可表达出入口的景片。',
    aliases: ['门洞景片'],
    relations: [relation('narrower_than', 'scenic-flat'), relation('supports', 'entrance')],
    executableIntents: ['place_door_flat'],
    confidence: 0.67,
  },
  {
    id: 'window-flat',
    label: '窗景片',
    definition: '带窗洞或窗框构造、可形成视线或采光开口的景片。',
    aliases: ['窗洞景片'],
    relations: [relation('narrower_than', 'scenic-flat'), relation('supports', 'sightline')],
    executableIntents: ['place_window_flat'],
    confidence: 0.67,
  },
  {
    id: 'flat-panel',
    executionEligibility: 'proposal_only',
    label: '景片片面',
    definition: '联片景片中可单独形成方向和表面的一个片段。',
    aliases: ['片面', '景片面板'],
    relations: [relation('part_of', 'scenic-flat')],
    confidence: 0.62,
  },
  {
    id: 'flat-frame',
    executionEligibility: 'proposal_only',
    label: '景片框架',
    definition: '支撑景片表面并保持形状的结构骨架。',
    aliases: ['景片骨架'],
    relations: [relation('part_of', 'scenic-flat')],
    confidence: 0.61,
  },
  {
    id: 'hinge',
    label: '铰链',
    definition: '允许相邻景片片面绕共同连接轴改变夹角的活动连接件。',
    aliases: ['合页', '活页'],
    relations: [relation('supports', 'fold-flat'), relation('related_to', 'join')],
    executableIntents: ['set_hinge_angle'],
    confidence: 0.65,
  },
  {
    id: 'join',
    conceptKind: 'operation',
    label: '连接',
    definition: '在两个舞台构件之间建立结构或空间关联的操作关系。',
    aliases: ['相连'],
    relations: [relation('broader_than', 'splice'), relation('related_to', 'hinge')],
    executableIntents: ['connect_assets'],
    confidence: 0.69,
  },
  {
    id: 'splice',
    conceptKind: 'operation',
    label: '拼接',
    definition: '把两个片面或构件沿边界连续组合成较大表面的连接方式。',
    aliases: ['接拼', '拼合', 'connect-edge'],
    relations: [relation('narrower_than', 'join'), relation('supports', 'edge-align')],
    executableIntents: ['splice_flats'],
    confidence: 0.66,
  },
  {
    id: 'fold-flat',
    conceptKind: 'operation',
    label: '景片折叠',
    definition: '保持联片整体位置关系，通过铰接处改变相邻片面夹角。',
    aliases: ['折叠景片', '把景片折起来', 'fold-hinge'],
    relations: [relation('distinct_from', 'rotate-whole'), relation('supports', 'enclosure')],
    contrastExamples: ['整件景片作为一个刚体一起转向属于整件旋转。'],
    executableIntents: ['fold_flat'],
    confidence: 0.7,
  },
  {
    id: 'rotate-whole',
    conceptKind: 'operation',
    label: '整件旋转',
    definition: '保持构件内部形状不变，使整个舞台物件绕统一轴转向。',
    aliases: ['整体旋转', '整组转动'],
    relations: [relation('distinct_from', 'fold-flat'), relation('related_to', 'angle')],
    contrastExamples: ['只改变联片铰链夹角属于景片折叠。'],
    executableIntents: ['rotate_asset'],
  },
  {
    id: 'align',
    conceptKind: 'operation',
    label: '对齐',
    definition: '使两个或多个对象在指定轴线、边界或参照方向上形成一致关系。',
    aliases: ['排齐'],
    relations: [relation('broader_than', 'edge-align')],
    executableIntents: ['align_assets'],
  },
  {
    id: 'edge-align',
    conceptKind: 'operation',
    label: '贴边',
    definition: '使一个对象的指定边靠近并对齐另一个对象的边界。',
    aliases: ['沿边贴合', '边对边'],
    relations: [relation('narrower_than', 'align'), relation('supports', 'splice')],
    executableIntents: ['align_edge'],
    confidence: 0.7,
  },
  {
    id: 'angle',
    conceptKind: 'spatial_relation',
    label: '角度',
    definition: '两个方向、片面或对象朝向之间的转角关系。',
    aliases: ['夹角', '转角'],
    relations: [relation('related_to', 'fold-flat'), relation('related_to', 'rotate-whole')],
    executableIntents: ['set_angle'],
  },
  {
    id: 'enclosure',
    conceptKind: 'operation',
    label: '围合',
    definition: '由多个对象或片面共同界定出相对封闭空间的布局关系。',
    aliases: ['围成', '合围'],
    relations: [relation('related_to', 'opening'), relation('supports', 'inside')],
    executableIntents: ['enclose_region'],
    confidence: 0.72,
  },
  {
    id: 'opening',
    conceptKind: 'spatial_relation',
    label: '开口',
    definition: '围合边界中供通行、观看或空间联通的未封闭部分。',
    aliases: ['缺口', '空间开口'],
    relations: [relation('related_to', 'enclosure'), relation('supports', 'entrance')],
    executableIntents: ['preserve_opening'],
    confidence: 0.72,
  },
])

const activeSpatial = concepts(
  'spatial_directing',
  'ACTIVE',
  'stage_term',
  'allowed',
  spatialRefs,
  [
    {
      id: 'stage-space',
      executionEligibility: 'proposal_only',
      label: '舞台空间',
      definition: '演出中由舞台边界、物件、表演者与观众观看关系共同组织的行动空间。',
      aliases: ['演出空间'],
      relations: [relation('broader_than', 'stage-left'), relation('broader_than', 'stage-center')],
    },
    {
      id: 'stage-left',
      label: '台左',
      canonicalLabel: '舞台左',
      authorityTier: 'institutional_teaching',
      definitionStatus: 'canonical',
      tradition: 'professional_stagecraft',
      authorityRefs: [UAF_STAGE_TERMS],
      definition: '以表演者面向观众时为基准的舞台左侧。',
      aliases: ['舞台左', '舞台左侧', '左边'],
      relations: [
        relation('opposite_of', 'stage-right'),
        relation('distinct_from', 'audience-left'),
        relation('same_spatial_side_as', 'audience-right'),
      ],
      positiveExamples: ['“把椅子放到台左”使用表演者面向观众的方向基准。'],
      contrastExamples: ['“观众左”使用观众面向舞台的相反方向基准。'],
      executableIntents: ['place_stage_left'],
    },
    {
      id: 'stage-right',
      label: '台右',
      canonicalLabel: '舞台右',
      authorityTier: 'institutional_teaching',
      definitionStatus: 'canonical',
      tradition: 'professional_stagecraft',
      authorityRefs: [UAF_STAGE_TERMS],
      definition: '以表演者面向观众时为基准的舞台右侧。',
      aliases: ['舞台右', '舞台右侧', '右边'],
      relations: [
        relation('opposite_of', 'stage-left'),
        relation('distinct_from', 'audience-right'),
        relation('same_spatial_side_as', 'audience-left'),
      ],
      executableIntents: ['place_stage_right'],
    },
    {
      id: 'upstage',
      label: '台后',
      canonicalLabel: '舞台后部',
      authorityTier: 'institutional_teaching',
      definitionStatus: 'canonical',
      tradition: 'professional_stagecraft',
      authorityRefs: [UAF_STAGE_TERMS],
      definition: '舞台上相对远离观众的一侧。',
      aliases: ['舞台后部', '上场口方向', '后面'],
      relations: [relation('opposite_of', 'downstage'), relation('related_to', 'background')],
      executableIntents: ['place_upstage'],
    },
    {
      id: 'downstage',
      label: '台前',
      canonicalLabel: '舞台前部',
      authorityTier: 'institutional_teaching',
      definitionStatus: 'canonical',
      tradition: 'professional_stagecraft',
      authorityRefs: [UAF_STAGE_TERMS],
      definition: '舞台上相对靠近观众的一侧。',
      aliases: ['舞台前部', '前台方向', '前面'],
      relations: [relation('opposite_of', 'upstage'), relation('related_to', 'foreground')],
      executableIntents: ['place_downstage'],
    },
    {
      id: 'audience-direction',
      label: '观众方向',
      definition: '从舞台向观众席观看的基准方向，用于解释面向和左右参照。',
      aliases: ['朝向观众', '观众席方向'],
      relations: [relation('related_to', 'stage-left'), relation('related_to', 'stage-right')],
      executableIntents: ['face_audience'],
    },
    {
      id: 'audience-left',
      label: '观众左',
      authorityTier: 'institutional_teaching',
      definitionStatus: 'canonical',
      tradition: 'professional_stagecraft',
      authorityRefs: [UAF_STAGE_TERMS],
      definition: '以观众面向舞台时为基准的左侧。',
      aliases: ['观众席左侧', '左边'],
      relations: [
        relation('opposite_of', 'audience-right'),
        relation('distinct_from', 'stage-left'),
        relation('same_spatial_side_as', 'stage-right'),
      ],
      executableIntents: ['place_audience_left'],
    },
    {
      id: 'audience-right',
      label: '观众右',
      authorityTier: 'institutional_teaching',
      definitionStatus: 'canonical',
      tradition: 'professional_stagecraft',
      authorityRefs: [UAF_STAGE_TERMS],
      definition: '以观众面向舞台时为基准的右侧。',
      aliases: ['观众席右侧', '右边'],
      relations: [
        relation('opposite_of', 'audience-left'),
        relation('distinct_from', 'stage-right'),
        relation('same_spatial_side_as', 'stage-left'),
      ],
      executableIntents: ['place_audience_right'],
    },
    {
      id: 'stage-center',
      label: '舞台中心',
      definition: '舞台平面中作为居中参照的区域，而非必须等同于视觉焦点。',
      aliases: ['台中', '舞台中央'],
      relations: [relation('part_of', 'stage-space'), relation('distinct_from', 'focus')],
      executableIntents: ['place_stage_center'],
    },
    {
      id: 'entrance',
      label: '入口',
      definition: '表演者或物件能够进入当前演出空间的通行位置。',
      aliases: ['进场口', '进入口'],
      relations: [relation('opposite_of', 'exit'), relation('narrower_than', 'opening')],
      executableIntents: ['preserve_entrance'],
    },
    {
      id: 'exit',
      label: '出口',
      definition: '表演者或物件能够离开当前演出空间的通行位置。',
      aliases: ['退场口', '离场口'],
      relations: [relation('opposite_of', 'entrance'), relation('narrower_than', 'opening')],
      executableIntents: ['preserve_exit'],
    },
    {
      id: 'passage',
      label: '通道',
      definition: '连接两个位置并允许行动通过的连续空间。',
      aliases: ['行动通道', '过道'],
      relations: [relation('related_to', 'entrance'), relation('related_to', 'exit')],
      executableIntents: ['preserve_passage'],
    },
    {
      id: 'occlusion',
      conceptKind: 'spatial_relation',
      label: '遮挡',
      definition: '对象位于观看者与目标之间，使目标部分或全部不可见的空间关系。',
      aliases: ['遮蔽'],
      relations: [relation('opposite_of', 'sightline')],
      executableIntents: ['avoid_occlusion'],
    },
    {
      id: 'sightline',
      conceptKind: 'spatial_relation',
      label: '视线',
      definition: '从观看位置到目标之间需要保持可见的观察路径。',
      aliases: ['观看视线', '视线通路'],
      relations: [relation('opposite_of', 'occlusion'), relation('supports', 'focus')],
      executableIntents: ['preserve_sightline'],
    },
    {
      id: 'spatial-relation',
      executionEligibility: 'proposal_only',
      conceptKind: 'spatial_relation',
      label: '空间关系',
      definition: '对象之间由方向、距离、包含、遮挡或邻接构成的相对位置语义。',
      aliases: ['相对空间关系'],
      relations: [relation('broader_than', 'near'), relation('broader_than', 'inside')],
    },
    {
      id: 'foreground',
      conceptKind: 'spatial_relation',
      label: '前景',
      definition: '从观看方向看处于较近层次、通常先被感知的空间区域。',
      aliases: ['前层', '前面'],
      relations: [relation('opposite_of', 'background'), relation('related_to', 'downstage')],
      executableIntents: ['place_foreground'],
    },
    {
      id: 'background',
      conceptKind: 'spatial_relation',
      label: '背景',
      definition: '从观看方向看处于较远层次、承托主要行动的空间区域。',
      aliases: ['后景', '背景层'],
      relations: [relation('opposite_of', 'foreground'), relation('related_to', 'upstage')],
      executableIntents: ['place_background'],
    },
    {
      id: 'stage-within-stage',
      conceptKind: 'spatial_relation',
      label: '戏中舞台',
      definition: '在主要演出空间内部再设置一个被观看或表演的次级舞台。',
      aliases: ['舞台中的舞台', '台中台'],
      relations: [relation('narrower_than', 'stage-space')],
      executableIntents: ['place_inner_stage'],
    },
    {
      id: 'object-layout',
      executionEligibility: 'proposal_only',
      conceptKind: 'spatial_relation',
      label: '物件布局',
      definition: '多个舞台物件的位置、朝向、距离和层次形成的整体配置。',
      aliases: ['道具布局', '舞台物件布置'],
      relations: [
        relation('related_to', 'spatial-relation'),
        relation('supports', 'stage-composition'),
      ],
    },
    {
      id: 'near',
      conceptKind: 'spatial_relation',
      label: '靠近',
      definition: '两个对象之间距离较小的相对空间关系，不预设接触。',
      aliases: ['接近', '挨近', 'near-object'],
      relations: [relation('opposite_of', 'far'), relation('narrower_than', 'spatial-relation')],
      executableIntents: ['place_near'],
    },
    {
      id: 'far',
      conceptKind: 'spatial_relation',
      label: '远离',
      definition: '两个对象之间距离增大的相对空间关系。',
      aliases: ['离远', '拉开距离'],
      relations: [relation('opposite_of', 'near'), relation('narrower_than', 'spatial-relation')],
      executableIntents: ['place_far'],
    },
    {
      id: 'inside',
      conceptKind: 'spatial_relation',
      label: '内部',
      definition: '对象位于另一空间边界或围合范围之内的关系。',
      aliases: ['里面', '之内'],
      relations: [
        relation('opposite_of', 'outside'),
        relation('narrower_than', 'spatial-relation'),
      ],
      executableIntents: ['place_inside'],
    },
    {
      id: 'outside',
      conceptKind: 'spatial_relation',
      label: '外部',
      definition: '对象位于另一空间边界或围合范围之外的关系。',
      aliases: ['外面', '之外'],
      relations: [relation('opposite_of', 'inside'), relation('narrower_than', 'spatial-relation')],
      executableIntents: ['place_outside'],
    },
  ],
)

const observeDirecting = concepts(
  'directing',
  'OBSERVE',
  'theory_concept',
  'proposal_only',
  directingRefs,
  [
    {
      id: 'blocking',
      label: '舞台调度',
      canonicalLabel: 'blocking',
      definition: '对表演者在舞台上的位置、移动和行动路线进行安排。',
      aliases: ['调度', '演员调度'],
      relations: [
        relation('supports', 'stage-picture'),
        relation('distinct_from', 'mise-en-scene'),
      ],
      definitionStatus: 'translation_variant',
      authorityTier: 'institutional_teaching',
      authorityRefs: [UAF_STAGE_TERMS],
      tradition: 'anglophone_stage_practice',
      disputedNotes: [
        '中文“舞台调度”常对应 blocking，但不能据此与更综合的 mise-en-scène 完全等同。',
      ],
    },
    {
      id: 'focus',
      label: '焦点',
      definition: '在特定舞台时刻引导观众主要注意力的对象或区域。',
      aliases: ['舞台焦点'],
      relations: [relation('related_to', 'center-of-interest')],
    },
    {
      id: 'stage-action',
      label: '舞台动作',
      definition: '在舞台上可被感知的具体动作表现。',
      aliases: ['外部舞台动作'],
      relations: [relation('distinct_from', 'dramatic-action')],
    },
    {
      id: 'dramatic-action',
      label: '舞台行动',
      definition: '人物为改变处境或影响对象而实施的有目的戏剧行动。',
      aliases: ['戏剧行动'],
      relations: [relation('distinct_from', 'stage-action')],
    },
    {
      id: 'through-action',
      label: '贯穿行动',
      canonicalLabel: 'through action',
      definition: '在斯坦尼斯拉夫斯基体系中，连接角色或演出各段任务并指向最高任务的持续行动线。',
      aliases: ['贯串行动', '贯穿动作', '贯串动作'],
      relations: [
        relation('opposite_of', 'counter-through-action'),
        relation('supports', 'super-objective'),
      ],
      definitionStatus: 'translation_variant',
      tradition: 'stanislavski_system',
      disputedNotes: ['四种中文写法归入同一 concept，不据字面“行动/动作”拆分。'],
      historicalAttributions: { proposers: ['康斯坦丁·斯坦尼斯拉夫斯基'] },
    },
    {
      id: 'counter-through-action',
      label: '反贯穿行动',
      canonicalLabel: 'counteraction',
      definition: '在斯坦尼斯拉夫斯基体系中，与贯穿行动形成阻力和对抗的行动线。',
      aliases: ['反贯串行动', '反贯穿动作', '反贯串动作'],
      relations: [relation('opposite_of', 'through-action')],
      definitionStatus: 'translation_variant',
      tradition: 'stanislavski_system',
      historicalAttributions: { proposers: ['康斯坦丁·斯坦尼斯拉夫斯基'] },
    },
    {
      id: 'super-objective',
      label: '最高任务',
      canonicalLabel: 'super-objective',
      definition: '斯坦尼斯拉夫斯基体系中统摄角色或演出全部行动方向的根本任务。',
      aliases: ['最高目标', '超任务'],
      relations: [relation('broader_than', 'stage-task')],
      definitionStatus: 'tradition_specific',
      tradition: 'stanislavski_system',
      disputedNotes: ['不是跨全部表演传统的通用顶层概念。'],
      historicalAttributions: { proposers: ['康斯坦丁·斯坦尼斯拉夫斯基'] },
    },
    {
      id: 'stage-task',
      label: '舞台任务',
      definition: '表演者在具体场景或行动段落中需要完成的目的性任务。',
      aliases: ['场景任务'],
      relations: [relation('narrower_than', 'super-objective')],
    },
    {
      id: 'stage-event',
      label: '舞台事件',
      definition: '在导演分析框架中，被选择为能够组织或转折舞台行动的重要事实。',
      relations: [relation('related_to', 'event')],
      definitionStatus: 'tradition_specific',
      tradition: 'director_analysis_pedagogy',
      disputedNotes: ['“改变人物关系或命运”可作为判别线索，但不作为所有传统中的必要定义条件。'],
    },
    {
      id: 'stage-conflict',
      label: '舞台冲突',
      definition: '通过行动、关系和场面组织被具体呈现的戏剧冲突。',
      relations: [relation('related_to', 'conflict')],
    },
    {
      id: 'stage-rhythm',
      label: '舞台节奏',
      definition: '演出中行动、停顿、转换和强弱变化形成的时间组织。',
      aliases: ['演出节奏'],
      relations: [relation('related_to', 'stage-tempo')],
    },
    {
      id: 'stage-atmosphere',
      label: '舞台气氛',
      definition: '由空间、行动、声音、光与表演共同形成的舞台感受。',
      aliases: ['演出气氛'],
    },
    {
      id: 'stage-tempo',
      label: '舞台速度',
      definition: '舞台行动推进的快慢状态，是节奏组织的一部分。',
      aliases: ['演出速度'],
      relations: [relation('related_to', 'stage-rhythm')],
    },
    {
      id: 'stage-composition',
      label: '舞台构图',
      definition: '人物与物件在观看画面中的位置、层次、方向和重心组织。',
      aliases: ['场面构图'],
      relations: [relation('supports', 'stage-picture')],
    },
    {
      id: 'stage-picture',
      label: '舞台画面',
      definition: '特定时刻由人物、物件、空间和视觉层次形成的整体可见状态。',
      aliases: ['舞台图景'],
      relations: [relation('related_to', 'stage-composition')],
    },
    {
      id: 'mise-en-scene',
      label: '场面调度',
      canonicalLabel: 'mise-en-scène',
      definition: '对表演、空间、布景、灯光等进入可见场面的要素进行综合组织。',
      aliases: ['场面处理', '舞台场面组织'],
      relations: [relation('related_to', 'blocking'), relation('distinct_from', 'blocking')],
      definitionStatus: 'translation_variant',
      authorityTier: 'institutional_teaching',
      authorityRefs: [COLUMBIA_MISE_EN_SCENE],
      tradition: 'francophone_directing_theory',
      disputedNotes: ['blocking 是其中与演员位置和移动有关的部分；两者不能合并为同一 concept。'],
    },
    {
      id: 'movement-line',
      label: '行动线',
      definition: '人物或物件在舞台空间中连续移动所形成的路径关系。',
      aliases: ['运动线'],
      relations: [relation('related_to', 'blocking')],
    },
    {
      id: 'center-of-interest',
      label: '注意中心',
      definition: '场面中最需要观众集中注意的感知中心。',
      aliases: ['兴趣中心'],
      relations: [relation('related_to', 'focus')],
    },
    {
      id: 'dynamic-balance',
      label: '动态平衡',
      definition: '通过不对称、方向张力或运动趋势形成的可变构图平衡。',
      relations: [relation('distinct_from', 'static-balance')],
    },
    {
      id: 'static-balance',
      label: '静态平衡',
      definition: '通过稳定、对称或均衡分布形成的构图平衡。',
      relations: [relation('distinct_from', 'dynamic-balance')],
    },
    {
      id: 'scene-transition',
      label: '场景转换',
      definition: '演出从一个场景空间或行动段落过渡到另一个的组织过程。',
      aliases: ['换景'],
    },
    {
      id: 'rehearsal',
      label: '排练',
      definition: '导演、演员及舞台部门逐步形成并检验演出方案的实践过程。',
      aliases: ['演出排练'],
    },
    {
      id: 'stage-synthesis',
      label: '舞台合成',
      definition: '把表演、空间、灯光、声音和舞台美术整合为统一演出的过程。',
      aliases: ['演出合成'],
    },
    {
      id: 'actor-scenery-relation',
      label: '人与景的关系',
      definition: '表演者的行动、尺度和位置与布景结构之间形成的关系。',
      aliases: ['演员与布景关系'],
    },
    {
      id: 'actor-audience-relation',
      label: '演员与观众关系',
      definition: '演出对表演者和观众之间观看、交流与距离方式的组织。',
      aliases: ['观演关系'],
    },
    {
      id: 'spatial-level',
      label: '空间层次',
      definition: '利用高度、深度或前后关系形成的舞台空间分层。',
      aliases: ['舞台层次'],
    },
    {
      id: 'group-composition',
      label: '群体构图',
      definition: '多个表演者作为群体在舞台画面中的排列与重心组织。',
      aliases: ['群像构图'],
    },
    {
      id: 'alienation-effect',
      label: '间离效果',
      canonicalLabel: 'Verfremdungseffekt',
      definition:
        '布莱希特史诗剧传统中，通过暴露建构方式、打断习惯化接受等手段，使观众保持可反思的观看距离。',
      aliases: ['陌生化效果', '陌生化', '间情法'],
      definitionStatus: 'translation_variant',
      authorityTier: 'institutional_teaching',
      authorityRefs: [UCF_BRECHT],
      tradition: 'brechtian_epic_theatre',
      disputedNotes: ['不定义为“完全不允许观众产生共鸣”；重点是阻断无批判的认同并促成判断。'],
      historicalAttributions: { proposers: ['贝托尔特·布莱希特'] },
    },
    {
      id: 'stage-zone',
      label: '舞台区位',
      definition: '为记录和分析调度而对舞台平面进行的工作性区域划分。',
      aliases: ['舞台区域', '舞台九区'],
      definitionStatus: 'heuristic',
      tradition: 'director_analysis_pedagogy',
      disputedNotes: [
        '九区划分可作教学工具；固定强弱顺序受剧场、构图、灯光与行动影响，不是普遍规律。',
      ],
    },
  ],
)

const observeDramaturgy = concepts(
  'dramaturgy',
  'OBSERVE',
  'theory_concept',
  'proposal_only',
  dramaturgyRefs,
  [
    {
      id: 'action',
      label: '行动',
      definition: '主体为达成目的并影响对象而实施的行为过程。',
      aliases: ['人物行动'],
    },
    {
      id: 'event',
      label: '事件',
      definition: '使处境或人物关系发生变化并推动行动发展的事实。',
      aliases: ['戏剧事件'],
    },
    {
      id: 'conflict',
      label: '冲突',
      definition: '彼此不相容的意志、目标或力量之间的对抗。',
      aliases: ['戏剧冲突'],
    },
    {
      id: 'character-relation',
      label: '人物关系',
      definition: '人物之间由身份、情感、利益和行动形成的相互联系。',
      aliases: ['角色关系'],
    },
    {
      id: 'given-circumstances',
      label: '规定情境',
      canonicalLabel: 'given circumstances',
      definition: '斯坦尼斯拉夫斯基体系中，剧作给定并由创作者补充、共同制约人物行动的事实与条件。',
      aliases: ['规定情景'],
      relations: [relation('distinct_from', 'dramatic-situation')],
      definitionStatus: 'tradition_specific',
      tradition: 'stanislavski_system',
      disputedNotes: ['不得与一般剧作分析中的“戏剧情境”合并。'],
      historicalAttributions: { proposers: ['康斯坦丁·斯坦尼斯拉夫斯基'] },
    },
    {
      id: 'dramatic-situation',
      label: '戏剧情境',
      canonicalLabel: 'dramatic situation',
      definition: '人物在具体时空、事件和关系条件中形成的戏剧性局面。',
      aliases: ['戏剧情景'],
      relations: [relation('distinct_from', 'given-circumstances')],
      definitionStatus: 'tradition_specific',
      tradition: 'chinese_theatre_studies',
      disputedNotes: [
        '这是剧作／戏剧理论概念，不等同于斯坦尼斯拉夫斯基体系的 given circumstances。',
      ],
    },
    {
      id: 'stage-situation',
      label: '舞台情境',
      definition: '规定情境在具体演出时刻经由空间和行动呈现出的现场处境。',
      aliases: ['场上情境'],
    },
    {
      id: 'plot',
      label: '情节',
      definition: '作品中事件按因果与时间关系组织形成的发展过程。',
      aliases: ['剧情'],
    },
    {
      id: 'theme',
      label: '主题',
      definition: '作品通过人物、事件和冲突集中探讨的核心意义。',
      aliases: ['戏剧主题'],
    },
    {
      id: 'dramatic-structure',
      label: '戏剧结构',
      definition: '戏剧材料、事件和行动段落之间的整体组织关系。',
      aliases: ['剧作结构'],
    },
    {
      id: 'dramaticity',
      label: '戏剧性',
      canonicalLabel: '戏剧性（中国戏剧理论用法）',
      definition: '中国戏剧理论讨论中，用来概括戏剧媒介、冲突、行动或情境所形成之戏剧特性的术语。',
      definitionStatus: 'tradition_specific',
      tradition: 'chinese_theatre_studies',
      disputedNotes: ['“假定情境中人物心理的直观外现”是特定理论表述，不是唯一的跨传统定义。'],
    },
    {
      id: 'black-slaves-cry-to-heaven',
      conceptKind: 'historical_entity',
      executionEligibility: 'knowledge_only',
      label: '《黑奴吁天录》',
      canonicalLabel: '《黑奴吁天录》（1907年舞台改编）',
      definition: '春柳社1907年依据《汤姆叔叔的小屋》相关中文译本进行改编和再创造的舞台作品。',
      aliases: ['黑奴吁天录'],
      authorityTier: 'peer_reviewed',
      definitionStatus: 'descriptive',
      tradition: 'early_chinese_spoken_drama_history',
      authorityRefs: [HZNU_BLACK_SLAVE_RESEARCH, TIAN_HAN_FOUNDATION_BLACK_SLAVE],
      disputedNotes: [
        '资料中“第一个创作剧本”的写法会误导为完全原创；应明确其 adaptation / re-creation 性质。',
      ],
      historicalAttributions: {
        participants: ['春柳社'],
        adapters: ['曾孝谷'],
      },
      sourceRefs: [
        {
          sourceId: SOURCE_IDS.zhongxi,
          locator: '第51页第933条《黑奴吁天录》',
          role: 'historical_terminology',
        },
        {
          sourceId: SOURCE_IDS.glossary2018,
          locator: '第54页第952条及相关春柳社条目',
          role: 'historical_terminology',
        },
      ],
    },
  ],
)

const futurePerformance = concepts(
  'performance',
  'FUTURE',
  'theory_concept',
  'knowledge_only',
  performanceRefs,
  [
    {
      id: 'character-objective',
      label: '人物目标',
      definition: '人物在具体情境中希望通过行动实现的结果。',
      aliases: ['角色目标'],
    },
    {
      id: 'acting-method',
      label: '表演方法',
      definition: '演员组织行动、体验、形体与表达以创造角色的实践路径总称。',
      aliases: ['演员方法'],
      definitionStatus: 'descriptive',
      disputedNotes: ['体验派／表现派是历史教学分类之一，不能作为覆盖所有表演方法的唯一顶层二分。'],
    },
    {
      id: 'subtext',
      label: '潜台词',
      definition: '台词字面之外由情境、关系和行动意图承载的含义。',
      aliases: ['言外之意'],
    },
    {
      id: 'monologue-training',
      label: '独白训练',
      definition: '围绕独白材料开展分析、行动与表达练习。',
      aliases: ['独白练习'],
    },
    {
      id: 'internal-monologue',
      label: '内心独白',
      definition: '角色在外部台词或行动背后持续展开的内部思想过程。',
      aliases: ['内部独白'],
    },
    {
      id: 'emotion-memory',
      label: '情绪记忆',
      definition: '演员调动既有情感经验以支持舞台体验的方法概念。',
      aliases: ['情感记忆'],
    },
    {
      id: 'imagination',
      label: '想象',
      definition: '演员对未直接存在的情境、对象和行动细节进行具体创造的能力。',
      aliases: ['艺术想象'],
    },
    {
      id: 'attention',
      label: '注意',
      definition: '演员在舞台上选择并维持对行动对象的心理指向。',
      aliases: ['舞台注意'],
    },
    {
      id: 'relaxation',
      label: '肌肉松弛',
      definition: '演员减少妨碍行动的多余身体紧张的训练要求。',
      aliases: ['放松训练'],
    },
    {
      id: 'stage-belief',
      label: '舞台信念',
      definition: '演员对虚构情境和行动逻辑建立真实可信感的能力。',
      aliases: ['真实感与信念'],
    },
    {
      id: 'communication',
      label: '交流',
      definition: '表演者与对象之间通过行动、注意和反应形成的相互影响。',
      aliases: ['舞台交流'],
    },
    {
      id: 'adaptation',
      label: '适应',
      definition: '表演者根据对象反应和情境变化调整行动方式的过程。',
      aliases: ['舞台适应'],
    },
    {
      id: 'physical-action',
      label: '形体行动',
      canonicalLabel: 'physical action',
      definition: '演员通过身体实施的、有目的且与心理过程相互作用的可见行动。',
      aliases: ['形体动作', '身体行动'],
      relations: [relation('related_to', 'psychological-action')],
      definitionStatus: 'tradition_specific',
      tradition: 'stanislavski_system',
      disputedNotes: ['可在分析中区分内外侧重，但不建成彼此隔绝的完全二元系统。'],
    },
    {
      id: 'psychological-action',
      label: '心理行动',
      canonicalLabel: 'psychological action',
      definition: '以影响意识、态度或关系为指向，并与可见身体行动相互作用的内在行动过程。',
      aliases: ['内心动作', '内部动作'],
      relations: [relation('related_to', 'physical-action')],
      definitionStatus: 'tradition_specific',
      tradition: 'stanislavski_system',
      disputedNotes: ['与形体行动可作分析性区分，但两者不构成互不相干的封闭二元。'],
    },
    {
      id: 'experiencing-school',
      label: '体验派',
      canonicalLabel: '体验派（历史教学分类）',
      definition: '近现代戏剧表演史与教学中，强调演员体验角色生活的一类历史性分类。',
      relations: [
        relation('related_to', 'acting-method'),
        relation('distinct_from', 'representation-school'),
      ],
      definitionStatus: 'tradition_specific',
      tradition: 'historical_acting_pedagogy',
      disputedNotes: ['不是所有表演方法的顶层类别，也不应把复杂实践压缩为单一“情感重于理智”。'],
      historicalAttributions: { participants: ['康斯坦丁·斯坦尼斯拉夫斯基'] },
    },
    {
      id: 'representation-school',
      label: '表现派',
      canonicalLabel: '表现派（历史教学分类）',
      definition: '近现代戏剧表演史与教学中，强调有意识组织外部表现形式的一类历史性分类。',
      relations: [
        relation('related_to', 'acting-method'),
        relation('distinct_from', 'experiencing-school'),
      ],
      definitionStatus: 'tradition_specific',
      tradition: 'historical_acting_pedagogy',
      disputedNotes: ['不是所有表演方法的顶层类别，也不能简化为演员在演出中完全没有体验。'],
      historicalAttributions: { participants: ['伯努瓦-康斯坦·科克兰'] },
    },
    {
      id: 'character-image',
      label: '人物形象',
      definition: '演员通过行动、形体、语言和关系创造的角色整体形象。',
      aliases: ['角色形象'],
    },
    {
      id: 'role-analysis',
      label: '角色分析',
      definition: '对角色目标、行动、关系和发展进行结构化理解的过程。',
      aliases: ['人物分析'],
    },
    {
      id: 'score-of-actions',
      label: '行动谱',
      definition: '把角色连续行动按任务、节拍与变化组织成可排练序列。',
      aliases: ['角色行动谱'],
    },
    {
      id: 'impulse',
      label: '行动冲动',
      definition: '促使角色采取下一步行动的即时内在驱力。',
      aliases: ['内在冲动'],
    },
    {
      id: 'emotional-expression',
      label: '情感表达',
      definition: '演员通过行动、声音和形体使人物情感被观众感知。',
      aliases: ['情绪表达'],
    },
    {
      id: 'observation',
      label: '观察生活',
      definition: '演员从现实人物和行为中积累角色创造素材的过程。',
      aliases: ['生活观察'],
    },
    {
      id: 'concentration',
      label: '注意集中',
      definition: '演员排除干扰并持续投入当前行动对象的能力。',
      aliases: ['专注训练'],
    },
    {
      id: 'sense-memory',
      label: '感觉记忆',
      definition: '演员对感官经验的回忆与再现能力。',
      aliases: ['感官记忆'],
    },
    {
      id: 'improvisation',
      label: '即兴表演',
      definition: '在给定条件下不依赖预先固定台词或动作进行即时创造。',
      aliases: ['即兴练习'],
    },
  ],
)

const futureVoice = concepts(
  'voice',
  'FUTURE',
  'theory_concept',
  'knowledge_only',
  performanceRefs,
  [
    {
      id: 'line-training',
      label: '台词训练',
      definition: '围绕语言行动、清晰度和表达组织开展的表演训练。',
      aliases: ['对白训练'],
    },
    {
      id: 'stress',
      label: '重音',
      definition: '为突出语义或行动重点而在语流中加强的词或音节。',
      aliases: ['逻辑重音'],
    },
    {
      id: 'pause',
      label: '停顿',
      definition: '语流中的暂时中断，可承担思考、节奏或行动转换功能。',
      aliases: ['语言停顿'],
    },
    {
      id: 'intonation',
      label: '语调',
      definition: '说话时音高、强弱和走向的组织变化。',
      aliases: ['声调变化'],
    },
    {
      id: 'breath',
      label: '气息',
      definition: '支持舞台发声、语句长度和声音控制的呼吸运用。',
      aliases: ['呼吸支持'],
    },
    {
      id: 'voice-projection',
      label: '声音投射',
      definition: '使声音清楚有效地到达演出空间中听众的发声能力。',
      aliases: ['声音送达'],
    },
    {
      id: 'resonance',
      label: '共鸣',
      definition: '借助身体共鸣腔体增强声音音量与音色的发声现象。',
      aliases: ['声音共鸣'],
    },
    {
      id: 'articulation',
      label: '吐字',
      definition: '通过口腔动作清晰形成语音并传达语言内容的能力。',
      aliases: ['咬字'],
    },
  ],
)

const allConcepts = [
  ...activeStageAssets,
  ...activeScenicFlats,
  ...activeSpatial,
  ...observeDirecting,
  ...observeDramaturgy,
  ...futurePerformance,
  ...futureVoice,
]

export const DIA_KNOWLEDGE_CATALOG: DiaKnowledgeCatalog = {
  version: VERSION,
  sources: [
    {
      sourceId: SOURCE_IDS.encyclopedia,
      title: '大百科考研表演、导演总结全面',
      sourceType: 'knowledge_source',
      domains: ['directing', 'dramaturgy', 'performance', 'stage_assets', 'spatial_directing'],
      localFileRef: 'D:/Obsidian/剧本资料/大百科考研表演，导演总结全面.docx',
      ingestionStatus: 'verified',
      version: 'local-2026-09-14',
      notes:
        'DOCX 正文与目录可提取；590 段、3 个一级标题。当前环境缺少受控 LibreOffice，因此未做分页渲染复核。',
    },
    {
      sourceId: SOURCE_IDS.mindmap,
      title: '导演学基础思维导图',
      sourceType: 'knowledge_source',
      domains: ['directing', 'dramaturgy', 'spatial_directing'],
      localFileRef: 'D:/Obsidian/剧本资料/导演学基础思维导图.pdf',
      ingestionStatus: 'verified',
      version: 'local-2026-09-14',
      notes: '1 页思维导图；文本可提取但线性化会损失层级，已结合整页视觉结构审计。',
    },
    {
      sourceId: SOURCE_IDS.zhongxi,
      title: '中央戏剧学院考研初试综合基础必背词条（2）',
      sourceType: 'knowledge_source',
      domains: ['directing', 'dramaturgy', 'performance', 'spatial_directing'],
      localFileRef: 'D:/Obsidian/剧本资料/中央戏剧学院考研初试综合基础必背词条 (2).pdf',
      ingestionStatus: 'verified',
      version: 'local-2026-09-14',
      notes: '51/51 页文本可提取；编号词条清晰。电影史等非本轮领域内容已排除。',
    },
    {
      sourceId: SOURCE_IDS.glossary2018,
      title: '词条2018版',
      sourceType: 'knowledge_source',
      domains: [
        'directing',
        'dramaturgy',
        'performance',
        'stage_assets',
        'scenic_flats',
        'spatial_directing',
      ],
      localFileRef: 'D:/Obsidian/剧本资料/词条2018版74页.pdf',
      ingestionStatus: 'verified',
      version: 'local-2026-09-14',
      notes: '74/74 页文本可提取；含页眉、水印、少量错字和重复词条，已在归一化阶段处理。',
    },
    {
      sourceId: SOURCE_IDS.seagull,
      title: '《海鸥》【俄】契诃夫',
      sourceType: 'example_source',
      domains: ['stage_assets', 'spatial_directing', 'dramaturgy'],
      localFileRef: 'D:/Obsidian/剧本资料/《海鸥》 【俄】契诃夫.pdf',
      ingestionStatus: 'verified',
      version: 'local-2026-09-14',
      notes: '40/40 页文本可提取；四幕开场舞台说明只进入场景案例，不参与 canonical definition。',
    },
    {
      sourceId: SOURCE_IDS.cyrano,
      title: '《西哈诺》CYRANO',
      sourceType: 'example_source',
      domains: ['stage_assets', 'spatial_directing', 'dramaturgy'],
      localFileRef: 'D:/Obsidian/剧本资料/西哈诺CYRANO.pdf',
      ingestionStatus: 'verified',
      version: 'local-2026-09-14',
      notes: '61/61 页文本可提取；中文字符间空格已仅在审计副本中归一，五幕场景只作为案例。',
    },
  ],
  concepts: allConcepts,
  sceneExamples: [
    {
      id: 'seagull-act-1-garden-stage',
      title: '《海鸥》第一幕：花园、湖与临时小舞台',
      conceptKind: 'example_pattern',
      definitionStatus: 'descriptive',
      executionEligibility: 'knowledge_only',
      sourceRef: {
        sourceId: SOURCE_IDS.seagull,
        locator: '第1页／第一幕开场舞台说明',
        role: 'example',
      },
      sceneDescription: '庄园花园面向湖岸，林荫道被一座临时小舞台截断。',
      stageObjects: ['临时小舞台', '幕布', '椅子', '小桌', '灌木'],
      entrances: ['由花园小路进入'],
      exits: ['沿花园小路离开'],
      directions: ['湖位于舞台背景方向'],
      spatialRelationships: ['小舞台与湖景形成前后层次', '椅子面向小舞台布置'],
      backgroundForeground: ['湖与远岸构成背景', '桌椅与灌木位于近景'],
      audienceStageRelation: ['剧中人物作为小舞台的观众'],
      objectLayout: ['小舞台横截林荫道', '桌椅散置在观看区域'],
      version: VERSION,
    },
    {
      id: 'seagull-act-2-lawn',
      title: '《海鸥》第二幕：槌球场草地',
      conceptKind: 'example_pattern',
      definitionStatus: 'descriptive',
      executionEligibility: 'knowledge_only',
      sourceRef: {
        sourceId: SOURCE_IDS.seagull,
        locator: '第12页／第二幕开场舞台说明',
        role: 'example',
      },
      sceneDescription: '庄园槌球场一带的草地仍与湖景相连。',
      stageObjects: ['长凳', '桌子', '椅子'],
      entrances: ['由庄园方向进入草地'],
      exits: ['向湖或庄园方向离开'],
      directions: ['湖作为远处方向参照'],
      spatialRelationships: ['长凳和桌椅形成停留区域'],
      backgroundForeground: ['湖在背景', '家具位于表演前层'],
      audienceStageRelation: ['自然环境按观众观看方向形成层次'],
      objectLayout: ['草地上的家具组织交谈位置'],
      version: VERSION,
    },
    {
      id: 'seagull-act-3-dining-room',
      title: '《海鸥》第三幕：庄园饭厅',
      conceptKind: 'example_pattern',
      definitionStatus: 'descriptive',
      executionEligibility: 'knowledge_only',
      sourceRef: {
        sourceId: SOURCE_IDS.seagull,
        locator: '第21页／第三幕开场舞台说明',
        role: 'example',
      },
      sceneDescription: '室内饭厅由门连接相邻房间，家具划分活动区域。',
      stageObjects: ['餐桌', '柜子', '椅子', '门'],
      entrances: ['经房门进入饭厅'],
      exits: ['经不同房门离开'],
      directions: ['门的位置构成行动方向'],
      spatialRelationships: ['餐桌与柜子限定人物通道'],
      backgroundForeground: ['柜子贴近室内边界', '餐桌形成主要前景'],
      audienceStageRelation: ['室内开口向观众揭示相邻空间'],
      objectLayout: ['桌子居于主要活动区，门与柜子沿边界布置'],
      version: VERSION,
    },
    {
      id: 'seagull-act-4-study',
      title: '《海鸥》第四幕：改作书房的客厅',
      conceptKind: 'example_pattern',
      definitionStatus: 'descriptive',
      executionEligibility: 'knowledge_only',
      sourceRef: {
        sourceId: SOURCE_IDS.seagull,
        locator: '第28页／第四幕开场舞台说明',
        role: 'example',
      },
      sceneDescription: '旧客厅被改作书房，门窗和家具共同界定工作与交谈区域。',
      stageObjects: ['书桌', '沙发', '书柜', '窗', '椅子', '门'],
      entrances: ['经通向其他房间的门进入'],
      exits: ['经房门离开书房'],
      directions: ['窗与门提供不同空间方向'],
      spatialRelationships: ['书桌、沙发与书柜形成多个活动中心'],
      backgroundForeground: ['书柜沿后部边界', '书桌和座椅进入主要表演层'],
      audienceStageRelation: ['家具布局保持室内行动对观众可见'],
      objectLayout: ['门窗沿边界，书桌、沙发和椅子组织内部空间'],
      version: VERSION,
    },
    {
      id: 'cyrano-act-1-theatre-hall',
      title: '《西哈诺》第一幕：勃艮第剧院大厅',
      conceptKind: 'example_pattern',
      definitionStatus: 'descriptive',
      executionEligibility: 'knowledge_only',
      sourceRef: {
        sourceId: SOURCE_IDS.cyrano,
        locator: '第1页／第一幕开场舞台说明',
        role: 'example',
      },
      sceneDescription: '剧院大厅内部包含正式舞台、楼座和观众活动区域，形成舞台中的舞台。',
      stageObjects: ['剧中舞台', '幕布', '脚灯', '长凳', '阶梯', '楼座'],
      entrances: ['观众由大厅入口进入', '演员由剧中舞台侧进入'],
      exits: ['观众可沿阶梯与通道离场'],
      directions: ['大厅地面、楼座与剧中舞台形成多方向观看关系'],
      spatialRelationships: ['宽阶梯连接地面与楼座', '长凳面对剧中舞台'],
      backgroundForeground: ['剧中舞台形成视觉深处', '观众席活动发生在前层'],
      audienceStageRelation: ['现实观众观看剧中观众，剧中观众再观看剧中舞台'],
      objectLayout: ['长凳排列于大厅，楼座环绕，阶梯贯通不同高度'],
      version: VERSION,
    },
    {
      id: 'cyrano-act-2-pastry-shop',
      title: '《西哈诺》第二幕：糕点铺',
      conceptKind: 'example_pattern',
      definitionStatus: 'descriptive',
      executionEligibility: 'knowledge_only',
      sourceRef: {
        sourceId: SOURCE_IDS.cyrano,
        locator: '第17页／第二幕开场舞台说明',
        role: 'example',
      },
      sceneDescription: '糕点铺的工作区、陈列区和顾客区域在同一室内并置。',
      stageObjects: ['柜台', '桌子', '椅子', '烤炉', '托盘'],
      entrances: ['顾客由店门进入'],
      exits: ['由店门离开'],
      directions: ['柜台内外形成行动方向'],
      spatialRelationships: ['柜台分隔工作者与顾客', '桌椅组织停留区'],
      backgroundForeground: ['烤炉和工作区偏后', '柜台与顾客区偏前'],
      audienceStageRelation: ['开放的店铺剖面让观众同时看见工作与交谈'],
      objectLayout: ['柜台构成主要边界，桌椅和烤炉分处两侧'],
      version: VERSION,
    },
    {
      id: 'cyrano-act-3-balcony-street',
      title: '《西哈诺》第三幕：罗克珊窗下的街道',
      conceptKind: 'example_pattern',
      definitionStatus: 'descriptive',
      executionEligibility: 'knowledge_only',
      sourceRef: {
        sourceId: SOURCE_IDS.cyrano,
        locator: '第33页／第三幕开场舞台说明',
        role: 'example',
      },
      sceneDescription: '夜间街道与上层阳台并置，形成上下两层行动空间。',
      stageObjects: ['房屋立面', '门', '窗', '阳台', '长凳'],
      entrances: ['人物由街道两端或房门进入'],
      exits: ['人物沿街道或经房门离开'],
      directions: ['阳台在上，街道在下'],
      spatialRelationships: ['阳台上的人物与街道人物形成垂直交流'],
      backgroundForeground: ['房屋立面构成背景', '街道行动位于前景'],
      audienceStageRelation: ['观众同时看见上下层人物'],
      objectLayout: ['门窗嵌于立面，阳台位于窗外上层'],
      version: VERSION,
    },
    {
      id: 'cyrano-act-4-siege-camp',
      title: '《西哈诺》第四幕：围城营地',
      conceptKind: 'example_pattern',
      definitionStatus: 'descriptive',
      executionEligibility: 'knowledge_only',
      sourceRef: {
        sourceId: SOURCE_IDS.cyrano,
        locator: '第46—47页／第四幕开场舞台说明',
        role: 'example',
      },
      sceneDescription: '战地营地以防御工事、散置物件和远方战线构成空间。',
      stageObjects: ['营帐', '武器', '鼓', '篝火', '防御工事'],
      entrances: ['士兵由营地或战线方向进入'],
      exits: ['向战线或营地深处离开'],
      directions: ['敌方战线构成远处方向'],
      spatialRelationships: ['防御工事分隔营地与战线', '散置物件形成曲折通道'],
      backgroundForeground: ['战线和地平线在背景', '营地人物与物件在前景'],
      audienceStageRelation: ['远近层次提示观众理解战场风险方向'],
      objectLayout: ['营帐、防御物和篝火组织士兵聚集区'],
      version: VERSION,
    },
    {
      id: 'cyrano-act-5-convent-garden',
      title: '《西哈诺》第五幕：修道院花园',
      conceptKind: 'example_pattern',
      definitionStatus: 'descriptive',
      executionEligibility: 'knowledge_only',
      sourceRef: {
        sourceId: SOURCE_IDS.cyrano,
        locator: '第54页／第五幕开场舞台说明',
        role: 'example',
      },
      sceneDescription: '修道院花园由树木、建筑开口和座椅形成安静的户外会面空间。',
      stageObjects: ['树木', '长凳', '修道院建筑', '门廊'],
      entrances: ['由修道院建筑或花园小路进入'],
      exits: ['沿门廊或花园小路离开'],
      directions: ['建筑与花园深处构成相反方向'],
      spatialRelationships: ['长凳位于可会面的开阔处', '树木与建筑围合花园'],
      backgroundForeground: ['修道院建筑作为背景边界', '长凳形成主要前景'],
      audienceStageRelation: ['花园开敞区域承载观众主要注意'],
      objectLayout: ['长凳、树木和门廊共同界定会面区与通道'],
      version: VERSION,
    },
  ],
  extraction: {
    pipeline: [
      'extract',
      'normalize',
      'deduplicate',
      'alias_merge',
      'relations',
      'source_refs',
      'confidence',
      'status',
    ],
    rawCandidateCount: 154,
    candidateConceptCount: allConcepts.length,
    activeCount: allConcepts.filter((concept) => concept.status === 'ACTIVE').length,
    observeCount: allConcepts.filter((concept) => concept.status === 'OBSERVE').length,
    futureCount: allConcepts.filter((concept) => concept.status === 'FUTURE').length,
    duplicateCount: 30,
    duplicateGroups: [
      ['舞台焦点', '焦点'],
      ['舞台区位', '舞台区域'],
      ['贯串动作', '贯穿行动'],
      ['最高任务', '最高目标'],
      ['舞台合成', '演出合成'],
      ['舞台调度', '调度'],
      ['戏剧冲突', '冲突'],
      ['人物行动', '行动'],
    ],
    conflictCount: 0,
    conflictConceptIds: [],
    coveredSourceIds: Object.values(SOURCE_IDS),
  },
}
