const assert = require('node:assert/strict')
const fs = require('node:fs')
const path = require('node:path')
const { chromium } = require(process.env.PLAYWRIGHT_MODULE || 'playwright')

async function main() {
  const base = process.env.BASE_URL || 'http://127.0.0.1:4318'
  const output = path.resolve('previews/simplified')
  fs.mkdirSync(output, { recursive: true })
  const browser = await chromium.launch({
    executablePath: process.env.CHROME_PATH,
    headless: true,
    args: ['--use-angle=swiftshader', '--enable-unsafe-swiftshader'],
  })
  const page = await browser.newPage({ viewport: { width: 1440, height: 900 } })
  const errors = [], checks = []
  page.on('pageerror', e => errors.push(e.message))
  await page.addInitScript(() => Object.defineProperty(navigator, 'gpu', { get: () => undefined }))
  const check = (name) => { checks.push(name); console.log(name) }
  const saved = async () => {
    await page.waitForFunction(() => document.querySelector('.studio-save-status')?.textContent === '已保存')
  }
  try {
    await page.goto(base, { waitUntil: 'domcontentloaded' })
    assert.equal(await page.locator('canvas').count(), 0)
    await page.screenshot({ path: path.join(output, 'home.png'), fullPage: true })
    await page.getByRole('button', { name: '新建舞台', exact: true }).click()
    await page.waitForURL('**/scene/**')
    const url = page.url(), id = new URL(url).pathname.split('/').at(-1)
    fs.writeFileSync(path.join(output, 'scene-id.txt'), id)
    check('Home has no Editor canvas; manual entry created an independent scene')
    await page.getByRole('button', { name: '置景', exact: true }).click()
    await page.getByLabel('剧目名称', { exact: true }).fill('简化排演 · 本轮验收')
    await saved()
    assert.equal(await page.locator('.cs-dock').count(), 0)
    await page.getByRole('button', { name: '排演', exact: true }).click()
    await page.getByRole('heading', { name: '模拟排演', exact: true }).waitFor()
    const rail = await page.locator('.diastage-tool-rail [data-tab-id]').evaluateAll(items => items.map(n => ({ id: n.dataset.tabId, box: n.getBoundingClientRect().toJSON() })))
    assert.deepEqual(rail.map(n => n.id), ['simulation','display','observe','record','versions'])
    assert.equal(rail[2].box.y, rail[3].box.y)
    assert.ok(rail[1].box.y < rail[2].box.y)
    assert.ok(rail[4].box.y > rail[3].box.y)
    check('Navigation order and Observe/Record shared row match the specification')
    await page.getByRole('button', { name: '添加人物标记', exact: true }).click()
    await page.getByLabel('人物名称', { exact: true }).fill('甲')
    await page.getByRole('button', { name: '平面', exact: true }).click()
    await page.getByRole('button', { name: '记录移动', exact: true }).click()
    const plane = page.locator('g[aria-label="模拟排演舞台图"] > polygon')
    const planeBox = await plane.boundingBox()
    await plane.click({ position: { x: planeBox.width / 2 + 45, y: planeBox.height / 2 } })
    await page.getByRole('button', { name: '完成路线', exact: true }).click()
    await saved()
    const stored = await (await page.request.get(base + '/api/scenes/' + id)).json()
    const doc = Object.values(stored.graph.nodes).find(n => n.type === 'site').metadata.diastageTheatre
    assert.equal(doc.version, 2)
    assert.equal(doc.rehearsalSimulation.paths.length, 1)
    assert.equal(doc.rehearsalSimulation.paths[0].points.length, 2)
    await page.screenshot({ path: path.join(output, 'route-2d.png') })
    await page.getByRole('button', { name: '播放排演', exact: true }).click()
    await page.waitForFunction(() => Number(document.querySelector('input[aria-label="排演时间"]').value) > .2)
    await page.getByRole('button', { name: '暂停排演', exact: true }).click()
    await page.getByRole('checkbox', { name: '循环', exact: true }).check()
    assert.equal(await page.getByRole('checkbox', { name: '循环', exact: true }).isChecked(), true)
    await page.getByRole('button', { name: '复位', exact: true }).click()
    check('Performer, 2D route creation, persistence, playback, pause and loop work')
    await page.getByRole('button', { name: '排演版本', exact: true }).click()
    await page.getByLabel('版本名称').fill('验收版本')
    await page.getByRole('button', { name: '保存当前版本', exact: true }).click()
    await saved()
    await page.getByRole('button', { name: '恢复此版本', exact: true }).click()
    check('Version save and restore are reachable')
    await page.getByRole('button', { name: '置景', exact: true }).click()
    await page.getByRole('button', { name: '舞台镜头', exact: true }).click()
    await page.getByRole('button', { name: '添加机位', exact: true }).click()
    await page.getByRole('button', { name: '从此机位观察', exact: true }).click()
    await page.getByRole('heading', { name: '观察', exact: true }).waitFor()
    await page.getByRole('button', { name: '停止并还原', exact: true }).waitFor()
    check('Camera can be created in SET and observed through the lazily loaded runtime')
    await page.getByRole('button', { name: '停止并还原', exact: true }).click()
    await page.getByRole('button', { name: '排演', exact: true }).click()
    await page.getByRole('button', { name: '三维', exact: true }).click()
    const cameraHint = page.getByRole('button', { name: '关闭摄像机操作提示', exact: true })
    if (await cameraHint.isVisible()) await cameraHint.click()
    await page.mouse.move(1400, 880)
    for (const [label,width,height] of [['desktop',1440,900],['ipad',768,1024],['small',390,844]]) {
      await page.setViewportSize({ width, height })
      await page.waitForFunction(() => document.documentElement.scrollWidth <= window.innerWidth)
      await page.waitForTimeout(1200)
      await page.screenshot({ path: path.join(output, label + '.png') })
    }
    check('Desktop, iPad and small layouts captured without document overflow')
    await page.setViewportSize({ width: 1440, height: 900 })
    await page.getByRole('button', { name: '复台', exact: true }).click()
    const steps = page.getByRole('navigation', { name: '复台步骤' }).getByRole('button')
    await steps.first().waitFor()
    assert.equal(await steps.count(), 6)
    for (let i = 0; i < 6; i++) { await steps.nth(i).click(); assert.equal(await steps.nth(i).getAttribute('aria-current'), 'step') }
    await steps.nth(0).click()
    await page.screenshot({ path: path.join(output, 'remount.png') })
    check('All six Remount steps remain reachable; application math and undo covered by unit tests')
    assert.equal(await page.locator('.cs-dock').count(), 0)
    assert.deepEqual(errors, [])
    fs.writeFileSync(path.join(output, 'browser.json'), JSON.stringify({ url, checks, errors }, null, 2))
  } catch (e) {
    await page.screenshot({ path: path.join(output, 'failure.png') }).catch(() => {})
    fs.writeFileSync(path.join(output, 'browser-failure.json'), JSON.stringify({ url:page.url(), checks, errors, error:String(e) }, null, 2))
    throw e
  } finally { await browser.close() }
}
main().catch(e => { console.error(e); process.exitCode = 1 })
